export const ACTION_TYPE = {
  SET_PRODUCT: "SET_PRODUCT",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_PRODUCT_RATING: "SET_PRODUCT_RATING",
  SET_PRODUCT_REVIEWS: "SET_PRODUCT_REVIEWS",
  REMOVE_REVIEW: "REMOVE_REVIEW",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_IS_MENU_VISIBLE: "SET_IS_MENU_VISIBLE",
  SET_IS_MODAL_OPEN: "SET_IS_MODAL_OPEN",
  SET_IS_PASSWORD_VISIBLE: "SET_IS_PASSWORD_VISIBLE",
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
};
