export const ACTION_TYPE = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_IS_MENU_VISIBLE: "SET_IS_MENU_VISIBLE",
  SET_IS_MODAL_OPEN: "SET_IS_MODAL_OPEN",
  SET_IS_PASSWORD_VISIBLE: "SET_IS_PASSWORD_VISIBLE",
  SET_USER: "SET_USER",
  LOGOUT: "LOGOUT",
};
